Left/Open_Palm: mouse_move|1.2
Left/Open_Palm+Right/Dis_Thumb_Index_Tip: mouse_press_left|30
Left/Open_Palm+Right/Dis_Thumb_Middle_Tip: mouse_press_right|30
Left/Closed_Fist+Right/Closed_Fist: lock
Left/Thumb_Up+Right/Thumb_Up: unlock